---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: container8.de/content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: container8.de/content
  label: Pages
  create: all
  match: "*"
upload_dir: container8.de//static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.49'
